//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmaRehberi.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campaigns
    {
        public int Id { get; set; }
        public string CampaignConditions { get; set; }
        public Nullable<System.DateTime> CampaignDate { get; set; }
        public System.DateTime AddedDate { get; set; }
        public string AdImage { get; set; }
        public Nullable<int> Companies_Id { get; set; }
        public string CompanyName { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Companies Companies { get; set; }
    }
}
