//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmaRehberi.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Companies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Companies()
        {
            this.AddToSite = new HashSet<AddToSite>();
            this.Campaigns = new HashSet<Campaigns>();
            this.Comments = new HashSet<Comments>();
            this.MembersCompanies = new HashSet<MembersCompanies>();
            this.PurchacingPackages = new HashSet<PurchacingPackages>();
            this.Showcases = new HashSet<Showcases>();
        }
    
        public int Id { get; set; }
        public string WorkingHours { get; set; }
        public string PaymentMethods { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<int> StarPoint { get; set; }
        public Nullable<int> StarGivenMemberCount { get; set; }
        public System.DateTime AddedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int Category_Id { get; set; }
        public string CompanyImage { get; set; }
        public Nullable<int> OpenOrClose { get; set; }
        public string CompanyName { get; set; }
        public string Adress { get; set; }
        public string City { get; set; }
        public string Town { get; set; }
        public string Brands { get; set; }
        public string Descriptions { get; set; }
        public string WebsiteName { get; set; }
        public Nullable<int> PurchasingPackage_Id { get; set; }
        public string NumberOfEmployees { get; set; }
        public string AuthorizedNameAndSurname { get; set; }
        public string AuthorizedDegree { get; set; }
        public string AuthorizedEmail { get; set; }
        public string Phone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AddToSite> AddToSite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Campaigns> Campaigns { get; set; }
        public virtual Categories Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comments> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MembersCompanies> MembersCompanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchacingPackages> PurchacingPackages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Showcases> Showcases { get; set; }
    }
}
