//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmaRehberi.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class MembersCompanies
    {
        public int Id { get; set; }
        public int Member_Id { get; set; }
        public Nullable<int> Company_Id { get; set; }
    
        public virtual Companies Companies { get; set; }
        public virtual Members Members { get; set; }
    }
}
