//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmaRehberi.db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class myPanelDBEntities : DbContext
    {
        public myPanelDBEntities()
            : base("name=myPanelDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AddToSite> AddToSite { get; set; }
        public virtual DbSet<Campaigns> Campaigns { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Comments> Comments { get; set; }
        public virtual DbSet<Companies> Companies { get; set; }
        public virtual DbSet<Members> Members { get; set; }
        public virtual DbSet<MembersCompanies> MembersCompanies { get; set; }
        public virtual DbSet<Packages> Packages { get; set; }
        public virtual DbSet<PurchacingPackages> PurchacingPackages { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Showcases> Showcases { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UsersRoles> UsersRoles { get; set; }
    }
}
