//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmaRehberi.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchacingPackages
    {
        public int Id { get; set; }
        public int PackageId { get; set; }
        public string BillingInfo { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public int Member_Id { get; set; }
        public string Adress { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<int> Company_Id { get; set; }
        public string TaxAdministration { get; set; }
        public string TaxNumber { get; set; }
        public Nullable<bool> isPurchasing { get; set; }
        public string CompanyName { get; set; }
    
        public virtual Companies Companies { get; set; }
        public virtual Packages Packages { get; set; }
    }
}
